# google_mlkit_text_recognition references optional per-language recognizers
# (Chinese/Devanagari/Japanese/Korean) that we don't bundle — R8 fails the
# release build on the missing classes without these suppressions. Generated by
# R8 itself (build/app/outputs/mapping/release/missing_rules.txt).
-dontwarn com.google.mlkit.vision.text.chinese.**
-dontwarn com.google.mlkit.vision.text.devanagari.**
-dontwarn com.google.mlkit.vision.text.japanese.**
-dontwarn com.google.mlkit.vision.text.korean.**
